# Generated by Django 4.2.3 on 2023-08-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_fotografia_usario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='usario',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
